/*Copyright (c) 2020-2021 TIREA All Rights Reserved.
 This software is the confidential and proprietary information of TIREA You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with TIREA*/
package es.tirea.wavemaker.consultaFacturas.desa.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class AllClientsResponse implements Serializable {


    @ColumnAlias("ID_CLIENTE")
    private String idCliente;

    public String getIdCliente() {
        return this.idCliente;
    }

    public void setIdCliente(String idCliente) {
        this.idCliente = idCliente;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof AllClientsResponse)) return false;
        final AllClientsResponse allClientsResponse = (AllClientsResponse) o;
        return Objects.equals(getIdCliente(), allClientsResponse.getIdCliente());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getIdCliente());
    }
}