/*Copyright (c) 2020-2021 TIREA All Rights Reserved.
 This software is the confidential and proprietary information of TIREA You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with TIREA*/
package es.tirea.wavemaker.consultaFacturas.desa.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class FacturaGraphResponse implements Serializable {


    @ColumnAlias("IMPORTE")
    private String importe;

    @ColumnAlias("FECHA_FACTURA")
    private String fechaFactura;

    public String getImporte() {
        return this.importe;
    }

    public void setImporte(String importe) {
        this.importe = importe;
    }

    public String getFechaFactura() {
        return this.fechaFactura;
    }

    public void setFechaFactura(String fechaFactura) {
        this.fechaFactura = fechaFactura;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof FacturaGraphResponse)) return false;
        final FacturaGraphResponse facturaGraphResponse = (FacturaGraphResponse) o;
        return Objects.equals(getImporte(), facturaGraphResponse.getImporte()) &&
                Objects.equals(getFechaFactura(), facturaGraphResponse.getFechaFactura());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getImporte(),
                getFechaFactura());
    }
}