/*Copyright (c) 2020-2021 TIREA All Rights Reserved.
 This software is the confidential and proprietary information of TIREA You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with TIREA*/
package es.tirea.wavemaker.consultaFacturas.desa.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class FacturasClienteResponse implements Serializable {


    @ColumnAlias("ID_FACTURA")
    private Integer idFactura;

    @ColumnAlias("FECHA_FACTURA")
    private String fechaFactura;

    @ColumnAlias("NUM_FACTURA")
    private String numFactura;

    @ColumnAlias("ID_SERVICIO")
    private String idServicio;

    @ColumnAlias("CLASE")
    private String clase;

    @ColumnAlias("IMPORTE")
    private BigDecimal importe;

    public Integer getIdFactura() {
        return this.idFactura;
    }

    public void setIdFactura(Integer idFactura) {
        this.idFactura = idFactura;
    }

    public String getFechaFactura() {
        return this.fechaFactura;
    }

    public void setFechaFactura(String fechaFactura) {
        this.fechaFactura = fechaFactura;
    }

    public String getNumFactura() {
        return this.numFactura;
    }

    public void setNumFactura(String numFactura) {
        this.numFactura = numFactura;
    }

    public String getIdServicio() {
        return this.idServicio;
    }

    public void setIdServicio(String idServicio) {
        this.idServicio = idServicio;
    }

    public String getClase() {
        return this.clase;
    }

    public void setClase(String clase) {
        this.clase = clase;
    }

    public BigDecimal getImporte() {
        return this.importe;
    }

    public void setImporte(BigDecimal importe) {
        this.importe = importe;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof FacturasClienteResponse)) return false;
        final FacturasClienteResponse facturasClienteResponse = (FacturasClienteResponse) o;
        return Objects.equals(getIdFactura(), facturasClienteResponse.getIdFactura()) &&
                Objects.equals(getFechaFactura(), facturasClienteResponse.getFechaFactura()) &&
                Objects.equals(getNumFactura(), facturasClienteResponse.getNumFactura()) &&
                Objects.equals(getIdServicio(), facturasClienteResponse.getIdServicio()) &&
                Objects.equals(getClase(), facturasClienteResponse.getClase()) &&
                Objects.equals(getImporte(), facturasClienteResponse.getImporte());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getIdFactura(),
                getFechaFactura(),
                getNumFactura(),
                getIdServicio(),
                getClase(),
                getImporte());
    }
}