/*Copyright (c) 2020-2021 TIREA All Rights Reserved.
 This software is the confidential and proprietary information of TIREA You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with TIREA*/
package es.tirea.wavemaker.consultaFacturas.desa;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Receptores generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`RECEPTORES`")
public class Receptores implements Serializable {

    private Integer idReceptor;
    private String tipoReceptor;
    private String tipoResidente;
    private String idFiscal;
    private String razonSocial;
    private String direccion;
    private String codPostal;
    private String ciudad;
    private String provincia;
    private String codPais;

    @Id
    @Column(name = "`ID_RECEPTOR`", nullable = false, scale = 0, precision = 10)
    public Integer getIdReceptor() {
        return this.idReceptor;
    }

    public void setIdReceptor(Integer idReceptor) {
        this.idReceptor = idReceptor;
    }

    @Column(name = "`TIPO_RECEPTOR`", nullable = false, length = 1)
    public String getTipoReceptor() {
        return this.tipoReceptor;
    }

    public void setTipoReceptor(String tipoReceptor) {
        this.tipoReceptor = tipoReceptor;
    }

    @Column(name = "`TIPO_RESIDENTE`", nullable = false, length = 1)
    public String getTipoResidente() {
        return this.tipoResidente;
    }

    public void setTipoResidente(String tipoResidente) {
        this.tipoResidente = tipoResidente;
    }

    @Column(name = "`ID_FISCAL`", nullable = false, length = 30)
    public String getIdFiscal() {
        return this.idFiscal;
    }

    public void setIdFiscal(String idFiscal) {
        this.idFiscal = idFiscal;
    }

    @Column(name = "`RAZON_SOCIAL`", nullable = true, length = 80)
    public String getRazonSocial() {
        return this.razonSocial;
    }

    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }

    @Column(name = "`DIRECCION`", nullable = true, length = 80)
    public String getDireccion() {
        return this.direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    @Column(name = "`COD_POSTAL`", nullable = true, length = 5)
    public String getCodPostal() {
        return this.codPostal;
    }

    public void setCodPostal(String codPostal) {
        this.codPostal = codPostal;
    }

    @Column(name = "`CIUDAD`", nullable = true, length = 50)
    public String getCiudad() {
        return this.ciudad;
    }

    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }

    @Column(name = "`PROVINCIA`", nullable = true, length = 20)
    public String getProvincia() {
        return this.provincia;
    }

    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }

    @Column(name = "`COD_PAIS`", nullable = true, length = 3)
    public String getCodPais() {
        return this.codPais;
    }

    public void setCodPais(String codPais) {
        this.codPais = codPais;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Receptores)) return false;
        final Receptores receptores = (Receptores) o;
        return Objects.equals(getIdReceptor(), receptores.getIdReceptor());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getIdReceptor());
    }
}