/*Copyright (c) 2020-2021 TIREA All Rights Reserved.
 This software is the confidential and proprietary information of TIREA You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with TIREA*/
package es.tirea.wavemaker.consultaFacturas.desa.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.List;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.export.ExportOptions;

import es.tirea.wavemaker.consultaFacturas.desa.models.query.*;

public interface DESAQueryExecutorService {

    Page<FacturasClienteResponse> executeFacturasCliente(Boolean _all, List<String> idCliente, String fechaIni, String fechaFin, Pageable pageable);

    void exportFacturasCliente(Boolean _all, List<String> idCliente, String fechaIni, String fechaFin, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<AllClientsResponse> executeAllClients(Pageable pageable);

    void exportAllClients(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<FacturaGraphResponse> executeFacturaGraph(Boolean _all, List<String> idCliente, String fechaIni, String fechaFin, Pageable pageable);

    void exportFacturaGraph(Boolean _all, List<String> idCliente, String fechaIni, String fechaFin, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

}