package es.tirea.wavemaker.consultaFacturas.fileservice.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.wavemaker.runtime.file.model.DownloadResponse;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;
import es.tirea.wavemaker.consultaFacturas.fileservice.FileService;

/**
 * Controller object for domain model class {@link FileService}.
 * @see FileService
 */
@RestController
@Api(value = "FileController", description = "controller class for java service execution")
@RequestMapping("/file")
public class FileController {

    @Autowired
    private FileService fileService;

    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @RequestMapping(value = "/downloadPdf", method = RequestMethod.GET, produces = "application/octet-stream")
    public DownloadResponse getDownloadPdf(@RequestParam(value = "idFactura", required = false) Integer idFactura) throws Exception {
        return fileService.getDownloadPdf(idFactura);
    }

    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @RequestMapping(value = "/downloadPdfAsInLine", method = RequestMethod.GET, produces = "application/octet-stream")
    public DownloadResponse getDownloadPdfAsInLine(@RequestParam(value = "idFactura", required = false) Integer idFactura) throws Exception {
        return fileService.getDownloadPdfAsInLine(idFactura);
    }

    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @RequestMapping(value = "/downloadXml", method = RequestMethod.GET, produces = "application/octet-stream")
    public DownloadResponse getDownloadXml(@RequestParam(value = "idFactura", required = false) Integer idFactura) throws Exception {
        return fileService.getDownloadXml(idFactura);
    }

    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @RequestMapping(value = "/downloadXmlAsInLine", method = RequestMethod.GET, produces = "application/octet-stream")
    public DownloadResponse getDownloadXmlAsInLine(@RequestParam(value = "idFactura", required = false) Integer idFactura) throws Exception {
        return fileService.getDownloadXmlAsInLine(idFactura);
    }
}

